### ISSUE TITLE
[FEATURE]: Replace the core tab manager UI with a fully featured "file" management widget

### ISSUE THREAD

**Issue by munael** [lbragile/TabMerger#13]
### Is your feature request related to a problem? Please describe.
Managing many, many tabs. Eventually, you'll want to allow users to move and manipulate multiple tabs at once.

### Describe the solution you'd like
As a bit of future proofing, TabMerger could use something like an existing tree management widget. _Maybe_ (just an example), something like this: https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/Overview/React/Dark/

### Describe alternatives you've considered
Moving to Firefox and trying Simple Tab Groups :P

### Additional context
I'm assuming that TabMerger completely unloads merged tabs (for now). With more featured management tools in the extension, it could be used as a "shadow version" of the browsing session, allowing a user to keep aside tabs in an organized fashion until they're needed for the current session. This's a part of the full ability of Simple Tab Groups, and one part that Chrome is sorely missing on with its underdeveloped bookmarking and extension support (in this area).

**Comment by lbragile** [comment]
Hi @munael,

Thank you for the awesome suggestion!
I added this to the [todo](https://github.com/lbragile/TabMerger/projects/1#card-52527715) list.

Stay tuned 😊
