### ISSUE TITLE
[Feature] Tab Selection

### ISSUE THREAD

**Issue by MarFre22** [lbragile/TabMerger#2]
Hi @lbragile , Thank you again for your work!

I'm thinking about another tab selection. I think it will be nice if we can select the tabs individually to temporary buffer (visible to the user). 
This selection could be visible to the user at same time he selects them - automatically opens the bookmark's side tab, when finished changes the side tab's "theme" to the previous one or closes it.

What do you think about? 😁

Keep the good work 💪

**Comment by lbragile** [comment]
Hi @MarFre22,

Is this related to #3?

If not, could you please elaborate as I understand the logic of adding the  tabs to a temporary "buffer" on the screen, then submitting them to the bookmark menu as individual items, but do not follow this logic
>  when finished changes the side tab's "theme" to the previous one or closes it.

Is this referring to the "temporary buffer", that is reverting it back to being empty?

Thank you for the good question!

**Comment by MarFre22** [comment]
@lbragile 
Some clarifications and reformulations.

So, I was thinking about create an auxiliary TabMerger's page into the Firefox sidebar (where we can access bookmarks, sync tabs, browser history, etc) like other extensions do (eg: Bitwarden). This auxiliary sidebar will show TabMerger's groups. 
1. We could drag&drop every tab we want or two of them (start and end tabs in order to all the tabs between them) into the auxiliary sidebar. 
2. Also, a good idea is to automatically make a temporary group (into the TabMerger's new sidebar) and add to it the tabs we want by click on them with a pressed key. 
3. An Other option, is, with temporary group, click the tab and, after, press a key or , without temporary group, click on the auxiliary sidebar to add it to a group (because, it's nice first to see the page before add it).

The TabMerger's new sidebar will be activated:
a. by the user in 1. and 3. (3. -> to show the button to add the current tab/page)
b. automatically in 2. and 3. (3. -> click the tab and, after, press a key to add the current tab/page)
c. hot key

The TabMerger's new sidebar will disappear, will reveal the previous Firefox sidebar app/theme:
a. automatically
b. other hot key or the same as activation's hot key (pressed again)

This issue isn't related with https://github.com/lbragile/TabMerger/issues/3 , because if we do that, we can't see the bookmark's folders at the same time (with auxiliary TabMerger's page) into (same) the sidebar. 

The temporary buffer is the auxiliary TabMerger's page into the Firefox sidebar, but you can make it as a complement to TabMerger's main page by show TabMerger's groups and the possibility to manage them.

**Comment by lbragile** [comment]
@MarFre22,

Thank you for the clarification, I will take a look at this when all of the other (medium/high priority) features are integrated.

**Comment by MarFre22** [comment]
Thanks! 
Good work 💪
