### ISSUE TITLE
[FEATURE]: Delete all needs a confirm dialog to prevent accidents

### ISSUE THREAD

**Issue by SeanPedersen** [lbragile/TabMerger#21]
**Is your feature request related to a problem? Please describe.**
Just lost all my groups by accidentally clicking on delete all groups tooltip

**Describe the solution you'd like**
A dialog asking the user to confirm deletion of **all** groups to prevent accidents.

**Comment by lbragile** [comment]
@SeanPedersen Good idea, as this is a very destructive move, it makes sense to confirm.
Also this is complementary to [undo delete action](https://github.com/lbragile/TabMerger/projects/1#card-51997035).
Added to the todo list.

**Comment by lbragile** [comment]
@SeanPedersen Both confirmation for deleting all groups/tabs and "undo" functionality were added and will be available in v1.6.0. Closing the issue for now. Let me know if there are any other issues.
