### ISSUE TITLE
[FEATURE]: standard color sheme for new groups

### ISSUE THREAD

**Issue by ruru4143** [lbragile/TabMerger#22]
**Problem:**
Picking color is very hard for me.

**Solution:**
A settings option, which sets a standard color pallet for new groups. 
example colorslist [red, blue, green]
first opend group: red
second opend group: blue
theird opend group: green
forth opend group 

**Alternatives:**
Every opend group gets a random color of the colorlist

**Additional Context:**
I like the pastel colors scheme of this [youtube video](https://www.youtube.com/watch?v=9eXmYE49jxA)
there have to be inclusive colorscheme for different types of color blindness.

**Comment by lbragile** [comment]
@ruru4143 I am not sure how much this is needed on top of the current color customization. The color picker is pretty user friendly and you can set default colors in the settings menu. That said, I can keep this idea around for later iterations.

**Comment by lbragile** [comment]
@ruru4143, what about the following?

![colorpicker](https://user-images.githubusercontent.com/65437893/106972840-88f2a480-6706-11eb-9c15-9c1215ca211f.gif)

A predefined list of colors that can give you a wide variety of options.
If these are not enough, you can click "Other..." to see the default color picker.

Let me know what you think.

**Comment by lbragile** [comment]
I will assume v1.6.0 & v1.6.1 take care of this issue well. Closing now!

**Comment by ruru4143** [comment]
you completly missunderstood my request. I'm not talking about opening a new group and then picking a color.
IMHO the addon should automaticly assinge a nice color to the new group.

**Comment by lbragile** [comment]
@ruru4143 I did in fact understand your request, but TabMerger does provide a default group color option. Which would override what you are asking for. Thus allowing the user to simply pick a color from a predefined list, reduces their need to approximate a color when picking. Maybe in future versions, I will integrate color pallets from the settings.

**Comment by ruru4143** [comment]
ok
