### ISSUE TITLE
[FEATURE]: Restore Firefox Multi-Account-Container after reopening

### ISSUE THREAD

**Issue by ruru4143** [lbragile/TabMerger#23]
**Problem:**
If you merge a tab with a container und you reopen it, it has no container anymore.

**Solution:***
the tab should has the same container properties.

**Additional context**
I didn't found any good documentation how to do this, but these links might help: 
[Rob--W/bookmark-container-tab](https://github.com/Rob--W/bookmark-container-tab/blob/master/background.js)
[mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/)

**Comment by lbragile** [comment]
@ruru4143 Interesting. Is this a Firefox specific case? That is can it be integrated in Chrome as well? I know chrome has [groups](https://blog.google/products/chrome/manage-tabs-with-google-chrome/), but I do not think they separate the storage like containers do from my understanding.

**Comment by ruru4143** [comment]
I have no knowledge about chrome

**Comment by lbragile** [comment]
This seems to be a Firefox specific request. I would like to make features available on all supported browsers, otherwise the maintenance of different code bases becomes too overwhelming for me. Hope you understand.
