### ISSUE TITLE
[FEATURE]: Restore treestyletab hierarchy after reopen tabs

### ISSUE THREAD

**Issue by ruru4143** [lbragile/TabMerger#24]
**Problem:**
The tree style tab hierarchy gets destroyed when reopening the tabs

**Solution:**
Save and restore the hierarchy properties

**Additional context**
[repo: piroor/treestyletab](https://github.com/piroor/treestyletab)
[treestyle tabs addon api](https://github.com/piroor/treestyletab/wiki/API-for-other-addons)

**Comment by lbragile** [comment]
@ruru4143 This is something I am considering without any external API. In general I try to avoid external API (outside of Chrome API) to guarantee performance. Added a [todo item](https://github.com/lbragile/TabMerger/projects/1#card-53052390) for this.
