### ISSUE TITLE
[BUG?]: "Open Group" opens 2x tabs

### ISSUE THREAD

**Issue by daguilar133** [lbragile/TabMerger#27]
When using the Open Group function, all tabs in the group are reopened twice. The order when reopened for 3 tabs is ABCABC, not AABBCC.

1. Go to tab merger page
2. Click on Open Group
3. Tabs populate twice

**Expected behavior**
Tabs open twice.

Note: While reproducing behavior, tabs began to open 3 times and continued to open 3 times.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/79034455/107869118-493b6380-6e50-11eb-81fd-2e4a6b5bbeb0.png">

RE: Individual Tabs - Tabs open twice when selecting individual tabs to reopen within a group. 

- OS: MacOS Catalina 10.15.6
- Browser Firefox 84.0

**Comment by daguilar133** [comment]
After restarting Firefox the issue is no longer reproducible.

**Comment by lbragile** [comment]
@daguilar133 very strange, I cannot reproduce this error. What version of TabMerger does this happen on?

Note that the latest version is **v1.6.1**.

**Comment by daguilar133** [comment]
@lbragile  I am using v1.6.1. 
Added to Firefox on 12/13/21
Running smoothly now.

**Comment by lbragile** [comment]
@daguilar133  Is this still an issue? I wasn't able to reproduce this behavior until now.

If not, I will close.

**Comment by daguilar133** [comment]
@lbragile Have not seen it again. Feel free to close out.
