### ISSUE TITLE
[Feature] Merge Bookmarks (Add batch)

### ISSUE THREAD

**Issue by MarFre22** [lbragile/TabMerger#3]
Hi again @lbragile, 

I know that it isn't the main goal of this project, but I think that it would be nice that we could select tabs individually and add them at the same time to a folder into bookmark's side tab.
What do you think?

Keep up the good work 💪

**Comment by lbragile** [comment]
Hi @MarFre22,

If I understand correctly, a user will have the ability to add tabs from TabMerger to a specific bookmark folder (through TabMerger's extension page)? If so, I have added this as a feature request. 

Thank you!

**Comment by MarFre22** [comment]
@lbragile 
I was thinking a bit differently, but yours is better, thanks ;)
It will be great if we could drag&drop them into bookmark's side tab.

Thanks for your work :)
