### ISSUE TITLE
[Improvement] README's Mobile Design

### ISSUE THREAD

**Issue by MarFre22** [lbragile/TabMerger#4]
Hi @lbragile ,

It isn't an urgent task, if you have time, can you improve the README's design? 
because on the GitHub's mobile app (Android) it isn't great:
![IMG_20210103_010855.jpg](https://user-images.githubusercontent.com/51057236/103469782-23a34080-4d61-11eb-85ae-01d8f3f8b8e3.jpg)

Keep the good work 💪 💪

**Comment by lbragile** [comment]
Hi @MarFre22,

Thank you for letting me know. 
I was not aware that android makes the README look different.

Here is what it looks like on iOS:
![image](https://user-images.githubusercontent.com/65437893/103470145-36972000-4d23-11eb-9c89-82f2fd550c14.png)

**Comment by scahill2124** [comment]
![Screenshot_20210102-184002_Chrome](https://user-images.githubusercontent.com/76892041/103470895-9d213b80-4d2d-11eb-8eb4-56e650ebb9f5.jpg)
seems to be fixed.

**Comment by MarFre22** [comment]
Unfortunately not. It's on the GitHub's Android app main page (of the project).

**Comment by lbragile** [comment]
Hi @MarFre22, @scahill2124,

Since I don't have access to an android mobile device, could you adjust the README and make a pull request when the above issue is fixed?

Thanks in advance!

**Comment by MarFre22** [comment]
@lbragile @scahill2124 
After some testing, looks like the Github app is bugy rendering markdown on mobile.
![IMG_20210103_221643.jpg](https://user-images.githubusercontent.com/51057236/103490108-6b81a080-4e11-11eb-821f-20ba9e392e69.jpg)

**Comment by lbragile** [comment]
@MarFre22,

That is very strange as in the markdown I have set the image tags to be 48x48 pixels.

**Comment by MarFre22** [comment]
@lbragile 
Yes, I saw what you did. I think Github's app ignores some html design.

**Comment by lbragile** [comment]
@MarFre22,

I manually resized the images to 48x48 px in the latest commit, can you check if the issue still persists?
If not, I will close the issue.

**Comment by MarFre22** [comment]
@lbragile 
I made a pull request to improve the images. You can see the changes here: https://github.com/lbragile/TabMerger/pull/5 ;)
