### ISSUE TITLE
Cannot activate

### ISSUE THREAD

**Issue by kevin182** [lbragile/TabMerger#48]
I got the activation code via email. On the main page I clicked on the icon on the bottom of the left navigation area. I typed my email and the activation copy/paste. Nothing happened. Tried refreshing the page. Tried exit Edge and reopen. Tried 2 more times. 

Went into settings and clicked on 1 of the subscription links. It brought me back to the tier page where I now see my plan (Basic) does not say Select but Current now. I clicked on it bringing me to another screen where I could put in my activation code. I did so and clicked update. That did not work either.

**Comment by lbragile** [comment]
@kevin182 This was caused by a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue in Edge and should now be resolved 🎉
