### ISSUE TITLE
[BUG]: Merges Pinned Tabs (unwanted)

### ISSUE THREAD

**Issue by SeanPedersen** [lbragile/TabMerger#6]
**Describe the bug**
Tab Merger merges my pinned tabs, which is annoying. I would appreciate if the default behavior was to ignore my pinned tabs or at least make it an option. Other than that great project, keep it going!

**To Reproduce**

1. Open chome
2. Pin some tabs
3. Merge
4. See your pinned tabs gone...

**Expected behavior**
Ignore (don't merge) pinned tabs.

**Please include the following information:**

- OS: Arch Linux
- Browser: Brave (Chrome)
- Version: 1.18.78

**Comment by lbragile** [comment]
Hi @SeanPedersen,

Thanks for the input. This is already added on the [todo list](https://github.com/lbragile/TabMerger/projects/1#card-51997052), make sure to double check there as well prior to posting an issue.

By the way, `Version: 1.18.78`  should be related to TabMerger (not the browser).

I will modify the issues template accordingly.
