### ISSUE TITLE
[BUG]: Clipped Group Names

### ISSUE THREAD

**Issue by SeanPedersen** [lbragile/TabMerger#7]
**Describe the bug**
Too long tab group names get clipped. Probably a CSS related bug.

**To Reproduce**

1. Create a group
2. Change name to e.g. Machine Learning

**Expected behavior**
Display full group name up to where it fits (e.g. until Created: 10/01/2021).

**Screenshots**
![Screenshot-from-2021-01-10-11-46-38.png](https://i.postimg.cc/SkrknVNk/Screenshot-from-2021-01-10-11-46-38.png)

**Please include the following information:**
- OS: Arch Linux
- Browser: Brave (Chrome)
- Version: 1.18.78

**Additional context**

**Comment by lbragile** [comment]
Hi @SeanPedersen,

This is not necessarily a bug but rather a result of a limit being applied to the title length, see: [Initialization](https://github.com/lbragile/TabMerger/blob/master/src/Group/Group.js#L40) & [Enforcement](https://github.com/lbragile/TabMerger/blob/master/src/Group/Group.js#L74). 

I will look into making it longer (maybe 20 instead of 15 characters), but there must be a limit to avoid interference with other icons in the title bar of a group.

**Comment by SeanPedersen** [comment]
Hey thanks for the heads up. I agree there must be a limit for mobile devices but 15 is too small IMO. 20 sounds better!

**Comment by SeanPedersen** [comment]
Ideally you would rescale max size with available device width.

**Comment by lbragile** [comment]
@SeanPedersen,

Good point, I will look into doing that!
Added this as a `high priority` [item](https://github.com/lbragile/TabMerger/projects/1#card-52527341)

**Comment by SeanPedersen** [comment]
You could also resize font size as well with device size if you are not doing that already.

**Comment by lbragile** [comment]
@SeanPedersen that is also an option, but I prefer keeping the font size as is to avoid straining to see the text - unless there is no other option.

**Comment by lbragile** [comment]
@SeanPedersen the latest commit: e07971696603c94e5050027dd9ad97afe21b0af8 partially fixes this. Increasing the limit to 50 characters allows you to type the full width and uses `text-overflow` to add `...` if you surpassed the width.

Below are the results with 50 character limit as described above.

### 1920px width
![image](https://user-images.githubusercontent.com/65437893/105562435-f813d600-5cce-11eb-9f1d-c5cba5266d27.png)

### 1600px width
![image](https://user-images.githubusercontent.com/65437893/105562370-b8e58500-5cce-11eb-839e-6eef860b53c5.png)

### 1200px width
![image](https://user-images.githubusercontent.com/65437893/105562311-85a2f600-5cce-11eb-9d18-820a1e97f94b.png)

### 991px width
![image](https://user-images.githubusercontent.com/65437893/105562291-71f78f80-5cce-11eb-9c7e-cf5e17be4593.png)

Let me know what you think.

**Comment by lbragile** [comment]
I see the thumbs up on my last post. Thanks for the input - closing now!
