### ISSUE TITLE
[FEATURE]: Alternate Tab Names

### ISSUE THREAD

**Issue by Tyderion** [lbragile/TabMerger#8]
**Is your feature request related to a problem? Please describe.**
There are a lot of web pages which I remember but don't know the exact name of the page and I'd like to give "alternate names" or "nicknames" to tabs so that i can search for those instead of the actual name of the tab

**Describe the solution you'd like**
Show a text field with edit button for each tab where you can add a short description/alternate name which then can be used to find the tab, either manually or with the search function.
Clicking the alternate name keeps the same functionality as clicking the tab name directly, that is, open the tab.

**Describe alternatives you've considered**
It's a similar thing to the Todo [Tab Category](https://github.com/lbragile/TabMerger/projects/1#card-51996955) but the idea is that it is individual for each tab

**Additional context**
A simple (and ugly) mockup is here (please don't judge my photoshop skills 😓).
![image](https://user-images.githubusercontent.com/564247/104121403-3a87fb00-533e-11eb-9fc0-a5d1bab3f080.png)
It might make more sense to display the alternate name + icon on the left of the actual tab name, so that all icons (drag icon, remove icon, edit icon) are next to each other
Any design suggestions are obviously welcome :)

What do you think of this idea?

**Comment by lbragile** [comment]
Hi @Tyderion,

This is a good suggestion which is already in the [todo](https://github.com/lbragile/TabMerger/projects/1#card-51996955) list. 
Thank you for providing a mockup - this is also what I had in mind!

I think you idea of an editable input field makes sense, but I will have to see if there are any other alternatives before going with this. Note that this must be responsive down to ~990px width screen size and should not appear in the print friendly PDF document (unless it is a clickable link to filter tabs in which case it could).

**Comment by Tyderion** [comment]
Ah I see, then i misunderstood the tags todo item, I thought that would be like general tags, but that's already covered by the groups. I'll think about how this could be handled, maybe I'll have a better idea, one that works better on smaller screens (with long tab names)

**Comment by lbragile** [comment]
@Tyderion, great, I will wait for your input before proceeding with this item!

**Comment by Tyderion** [comment]
I thought a bit about this and there's some problems which this feature will run into regardless of the design.
The user can enter any text for the tags for each tab/url and that means, that there will be some point, where the design breaks due to the length of the entered tag.
So far I've only managed to think of a few mitigations for this problem:
1. Limit the length of text the user can enter (will still lead to problems with long tab names)
2. Limit the displayed length of tags (will be kind of weird when searching, because the part that is found may not be visible in the UI)
3. Allow a tab to take up more than 1 line of space, so that the tag can be visible
4. Or a combination of the above, e.g. show a max of 2 lines and truncate the length of tab & tag.

We could also do this in a different way, by allowing the user to edit the displayed name of a tab instead of adding tags. This would still face the length problem, but I think if a user wants to enter a super long string (which probably doesn't make a lot of sense in most cases) he should be able to do it and then the user will just have live with it.

I think I would prefer to be able to edit the displayed tab name and truncate the name at one line (which, depending on the screen size, is more or less text of course). Search would of course always search through the whole tab name / tag name, not just the displayed part

**Comment by lbragile** [comment]
@Tyderion I went with the "edit tab title" approach and simply used `text-overflow` css property to ensure length is not an issue. This will be available in v1.6.0, but you should see this in the [latest commit](https://github.com/lbragile/TabMerger/commit/0ec315999169c8a62ca01b38f27365da6bd962ad)!

I think this solves the core issue without over complicating the situation which I think adding "nicknames" beside each tab would do (as you also pointed out). Let me know what you think.

**Comment by lbragile** [comment]
I will assume v1.6.0 & v1.6.1 take care of this issue well. Closing now!

**Comment by Tyderion** [comment]
Cool, this looks perfect for my use case, thanks a lot for implementing this feature so fast 🥳
